
---
include:
  - board: xiao_ble
    shield: chalk_left 
    snippet: studio-rpc-usb-uart 
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    group: central
  - board: xiao_ble 
    shield: chalk_right  
  - board: xiao_ble 
    shield: settings_reset
    group: peripheral
