
---
include:

  - board: zongle
    shield: chalk_dongle
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

  - board: xiao_ble 
    shield: chalk_left 
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n


  - board: xiao_ble 
    shield: chalk_right  
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: xiao_ble 
    shield: settings_reset

  - board: zongle 
    shield: settings_reset

