
---
include:
  - board: seeeduino_xiao_ble
    shield: chalk_left 
    snippet: zmk-usb-logging
    group: central
  - board: seeeduino_xiao_ble
    shield: chalk_right  
  - board: seeeduino_xiao_ble
    shield: settings_reset
    group: peripheral
