
---
include:
  - board: xiao_ble
    shield: chalk_left 
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble 
    shield: chalk_right  
  - board: xiao_ble 
    shield: settings_reset
