
---
include:

  - board: zongle
    shield: chalk_dongle
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: xiao_ble 
    shield: chalk_left 

  - board: xiao_ble 
    shield: chalk_right  

  - board: xiao_ble 
    shield: settings_reset

  - board: zongle 
    shield: settings_reset

